# Generated by Django 5.2.5 on 2025-08-24 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('feautered', models.BooleanField(default=False)),
                ('update', models.BooleanField(default=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='boards.board')),
            ],
            options={
                'verbose_name': 'thread',
                'verbose_name_plural': 'threads',
            },
        ),
    ]
