# Generated by Django 5.2.5 on 2025-08-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
